### ISSUE TITLE
Updater VID, PID mismatch

### ISSUE THREAD

**Issue by JohnDMcMaster** [ProgHQ/open-tl866#35]
Old bootloader had some vid/pid as vendor firmware. When the updater ran, it expected to get the same vid/pid when updating to the open firmware. However, this is no longer the case, resulting in this warning. We should either disable or fix the check. Warning aside, the update does work

```
$ tl866 self update --reset-tty /dev/ttyACM0 dist/tl866-at89.hex
resetting to bootloader via serial
erasing
programming
success!
resetting to firmware
Traceback (most recent call last):
  File "/usr/local/bin/tl866", line 9, in <module>
    load_entry_point('pytl866', 'console_scripts', 'tl866')()
  File "/home/mcmaster/doc/ext/otl866/pytl866/pytl866/cli.py", line 15, in main
    args.func(args)
  File "/home/mcmaster/doc/ext/otl866/pytl866/pytl866/bootloader/cli.py", line 136, in cmd_update
    dev.reset()
  File "/home/mcmaster/doc/ext/otl866/pytl866/pytl866/bootloader/driver.py", line 105, in reset
    self.device.reopen()
  File "/home/mcmaster/doc/ext/otl866/pytl866/pytl866/bootloader/driver.py", line 65, in reopen
    (USB_VENDOR, USB_PRODUCT, dev.idVendor, dev.idProduct))
RuntimeError: wrong device reconnected after reset (exp: 04D8:E11C, got 1209:8661)
```

**Comment by JohnDMcMaster** [comment]
This was fixed in a recent commit
